# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='Dashboard Creation Date.')),
                ('in_use', models.BooleanField()),
            ],
        ),
    ]
