# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dashboard', '0001_initial'), ('dashboard', '0002_auto_20161126_2139'), ('dashboard', '0003_auto_20161128_2230'), ('dashboard', '0004_auto_20161128_2233'), ('dashboard', '0005_auto_20161129_1318'), ('dashboard', '0006_auto_20161129_1319'), ('dashboard', '0007_auto_20161129_1359'), ('dashboard', '0008_auto_20161129_1445'), ('dashboard', '0009_auto_20161129_1547'), ('dashboard', '0010_member_role'), ('dashboard', '0011_auto_20161129_1929'), ('dashboard', '0012_auto_20161129_1955'), ('dashboard', '0013_auto_20161129_2118'), ('dashboard', '0014_auto_20161129_2128'), ('dashboard', '0015_member_role'), ('dashboard', '0016_auto_20161129_2329'), ('dashboard', '0017_auto_20161129_2330'), ('dashboard', '0018_auto_20161204_0054'), ('dashboard', '0019_auto_20161204_1234'), ('dashboard', '0020_auto_20161204_1501'), ('dashboard', '0021_team_status'), ('dashboard', '0022_team_lrp_comment'), ('dashboard', '0023_member_comment'), ('dashboard', '0024_auto_20161205_2214')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=200, unique=True, verbose_name='Dashboard Name')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Dashboard Create Date')),
                ('advisory_end_date', models.DateField(verbose_name='End date of Advisory Process')),
                ('advisory_start_date', models.DateField(verbose_name='Start date of Advisory Process')),
                ('number_of_teams', models.IntegerField(verbose_name='Number of teams')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dashboards',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.RenameModel(
            old_name='Dashboards',
            new_name='Dashboard',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='dashboard_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dashboard Create Date'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Team Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='number_of_teams',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.Dashboard'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.Team'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=18, verbose_name='Role')),
                ('short_name', models.CharField(default='LRP', max_length=3, verbose_name='Short Name')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='dashboard.Role'),
        ),
        migrations.CreateModel(
            name='AdvisoryPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=200, verbose_name='Phases')),
                ('reached_in_week', models.IntegerField(verbose_name='Reached in Week')),
                ('expected_calls', models.IntegerField(verbose_name='Expected calls')),
            ],
        ),
        migrations.CreateModel(
            name='FellowSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit date')),
                ('call_date', models.DateField(verbose_name='Call date')),
                ('all_prepared', models.BooleanField(verbose_name='All participants prepared for call?')),
                ('topic_discussed', models.CharField(max_length=200, verbose_name='Topic Discussed')),
                ('help', models.CharField(blank=True, max_length=3000, verbose_name='Ashoka team should help with')),
                ('phase_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the phase going?')),
                ('other_comments', models.CharField(blank=True, max_length=3000, verbose_name='Any other comments?')),
                ('document_link', models.URLField(blank=True, verbose_name='Link to current document')),
                ('current_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='dashboard.AdvisoryPhase')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='receives_survey_reminder_emails',
            field=models.BooleanField(default=False, verbose_name='Receives reminder emails?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowsurvey',
            name='missing_member',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='fellowsurvey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='dashboard.Team'),
        ),
        migrations.RenameModel(
            old_name='FellowSurvey',
            new_name='ConsultantSurvey',
        ),
        migrations.CreateModel(
            name='FellowSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit date')),
                ('phase_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the advisory phase going?')),
                ('comments', models.CharField(blank=True, max_length=3000, verbose_name='Any other comments?')),
                ('other_help', models.CharField(blank=True, max_length=3000, verbose_name='Any other Ashoka should help with?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_surveys', to='dashboard.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='consultantsurvey',
            name='phase_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the advisory phase going?'),
        ),
        migrations.AlterField(
            model_name='consultantsurvey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_surveys', to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('RED', 'Major issues!!!'), ('YELLOW', 'Some minor issues!'), ('GREEN', 'All good!')], default='GREEN', max_length=7, verbose_name='Team Status'),
        ),
        migrations.AddField(
            model_name='team',
            name='lrp_comment',
            field=models.CharField(blank=True, max_length=4000, verbose_name='LRP Comment'),
        ),
        migrations.AddField(
            model_name='member',
            name='comment',
            field=models.CharField(blank=True, max_length=4000, verbose_name='comment'),
        ),
    ]
