# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 05:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=200, verbose_name='Phases')),
                ('reached_in_week', models.IntegerField(verbose_name='Reached in Week')),
                ('expected_calls', models.IntegerField(verbose_name='Expected calls')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit date')),
                ('call_date', models.DateField(verbose_name='Call date')),
                ('all_prepared', models.BooleanField(verbose_name='All participants prepared for call?')),
                ('topic_discussed', models.CharField(max_length=200, verbose_name='Topic Discussed')),
                ('help', models.CharField(blank=True, max_length=3000, verbose_name='Ashoka team should help with')),
                ('phase_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the advisory phase going?')),
                ('other_comments', models.CharField(blank=True, max_length=3000, verbose_name='Any other comments?')),
                ('document_link', models.URLField(blank=True, verbose_name='Link to current document')),
                ('current_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='dashboard.AdvisoryPhase')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Dashboard Name')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Dashboard Create Date')),
                ('advisory_start_date', models.DateField(verbose_name='Start date of Advisory Process')),
                ('advisory_end_date', models.DateField(verbose_name='End date of Advisory Process')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='FellowSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit date')),
                ('phase_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the advisory phase going?')),
                ('comments', models.CharField(blank=True, max_length=3000, verbose_name='Any other comments?')),
                ('other_help', models.CharField(blank=True, max_length=3000, verbose_name='Any other Ashoka should help with?')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('receives_survey_reminder_emails', models.BooleanField(verbose_name='Receives reminder emails?')),
                ('comment', models.CharField(blank=True, max_length=4000, verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3, verbose_name='Short Name')),
                ('long_name', models.CharField(max_length=18, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Team Name')),
                ('lrp_comment', models.CharField(blank=True, max_length=4000, verbose_name='LRP Comment')),
                ('status', models.CharField(choices=[('RED', 'Major issues!!!'), ('YELLOW', 'Some minor issues!'), ('GREEN', 'All good!')], default='GREEN', max_length=7, verbose_name='Team Status')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.Dashboard')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='dashboard.Role'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='fellowsurvey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_surveys', to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='consultantsurvey',
            name='missing_member',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='dashboard.Member'),
        ),
        migrations.AddField(
            model_name='consultantsurvey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_surveys', to='dashboard.Team'),
        ),
    ]
