# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_squashed_0030_remove_advisoryphase_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('AUTO', 'Automatic'), ('RED', 'Major issues!!!'), ('YELLOW', 'Some minor issues!'), ('GREEN', 'All good!')], default='GREEN', max_length=7, verbose_name='Team Status'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='unprepared_calls_r',
            field=models.IntegerField(help_text='If percentage of unprepared calls is less than this threshold, Red warning will be raised. ', verbose_name='% unprepared call threshold'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='unprepared_calls_y',
            field=models.IntegerField(help_text='If percentage of unprepared calls is less than this threshold, Yellow warning will be raised. ', verbose_name='% unprepared call threshold'),
        ),
    ]
