# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='in_use',
        ),
        migrations.AddField(
            model_name='dashboards',
            name='advisory_end_date',
            field=models.DateField(default=datetime.date(2016, 6, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboards',
            name='advisory_start_date',
            field=models.DateField(default=datetime.date(2016, 7, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboards',
            name='number_of_teams',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
