# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20161126_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboards',
            name='advisory_end_date',
            field=models.DateField(verbose_name='End date of Advisory Process'),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='advisory_start_date',
            field=models.DateField(verbose_name='Start date of Advisory Process'),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Dashboard Create Date'),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='dashboard_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Dashboard Name'),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='number_of_teams',
            field=models.IntegerField(verbose_name='Number of teams'),
        ),
    ]
