# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_secondaryrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryrole',
            name='short_name',
            field=models.CharField(default='PM', max_length=100),
            preserve_default=False,
        ),
    ]
