# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161128_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboards',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
    ]
