# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_secondaryrole_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secondary_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_role', to='dashboard.SecondaryRole'),
            preserve_default=False,
        ),
    ]
