# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161212_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='status_choices',
            new_name='status_choice',
        ),
    ]
