# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_member_secondary_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='secondary_role',
        ),
        migrations.AddField(
            model_name='member',
            name='secondary_role',
            field=models.ManyToManyField(related_name='secondary_role', to='dashboard.SecondaryRole'),
        ),
    ]
