# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20161212_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role_comment',
            field=models.TextField(blank=True, verbose_name='Role Comment'),
        ),
    ]
