# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20161129_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='dashboard_name',
            new_name='name',
        ),
    ]
