# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_member_role_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='receives_survey_reminder_emails',
        ),
    ]
