# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20161209_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject of the Email')),
                ('message', models.CharField(max_length=3000, verbose_name='Body of the Email')),
                ('type', models.CharField(choices=[('IM', 'Instruction Mail'), ('RM', 'Reminder Mail')], max_length=5, verbose_name='Type of Email')),
            ],
        ),
        migrations.AlterField(
            model_name='secondaryrole',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='secondaryrole',
            name='short_name',
            field=models.CharField(max_length=100, verbose_name='Short Name'),
        ),
    ]
