# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20161129_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dashboard Create Date'),
        ),
    ]
