# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_member_receives_survey_reminder_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekwarning',
            name='unprepared_calls_r',
            field=models.IntegerField(help_text='If percentage of unprepared calls is greater than this threshold, Red warning will be raised. ', verbose_name='% unprepared call threshold - Red warning'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='unprepared_calls_y',
            field=models.IntegerField(help_text='If percentage of unprepared calls is greater than this threshold, Yellow warning will be raised. ', verbose_name='% unprepared call threshold - Yellow warning'),
        ),
    ]
