# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20161129_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Team Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='number_of_teams',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_teams',
            field=models.IntegerField(default=12, verbose_name='Total number of teams'),
            preserve_default=False,
        ),
    ]
