# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20161212_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='participates_in_call',
            field=models.BooleanField(default=True, verbose_name='Pariticipates in Calls'),
        ),
    ]
