# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20161209_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(verbose_name='Body of the Email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject of the Email'),
        ),
    ]
