# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20161129_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='dashboard',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='total_members',
            field=models.IntegerField(default=6, verbose_name='Total Number of members in Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Team'),
        ),
    ]
