# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_member_participates_in_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('IM', 'Instruction Mail'), ('RM', 'Reminder Mail'), ('CR', 'Consultant form Request Mail'), ('FR', 'Fellow form Request Mail')], help_text='Type of the template.', max_length=5, verbose_name='Type'),
        ),
    ]
