# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20161209_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantsurvey',
            name='help',
            field=models.TextField(blank=True, verbose_name='Ashoka team should help with'),
        ),
        migrations.AlterField(
            model_name='consultantsurvey',
            name='other_comments',
            field=models.TextField(blank=True, verbose_name='Any other comments?'),
        ),
        migrations.AlterField(
            model_name='fellowsurvey',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Any other comments?'),
        ),
        migrations.AlterField(
            model_name='fellowsurvey',
            name='other_help',
            field=models.TextField(blank=True, verbose_name='Any other Ashoka should help with?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lrp_comment',
            field=models.TextField(blank=True, verbose_name='LRP Comment'),
        ),
    ]
