# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20161212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='reminder_emails_after',
            field=models.PositiveIntegerField(default=9, verbose_name='Reminder emails should be sent after this many days from last response submit'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(help_text="If you wish to include the url to consultant form in the email, please add '#FORM_URL#' (without quotes) placeholder.It will be replaced by the actual consultant url in the email.\nIf you wish to include the fellow/consultant request in the email please add #REQUEST# placeholder in the email body.", verbose_name='Body of the Email'),
        ),
    ]
