# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='total_teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='total_members',
        ),
    ]
