# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_teamstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatus',
            name='call_change_count',
            field=models.IntegerField(default=0, verbose_name='Add/Subtract Total Calls count'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='kick_off_comment',
            field=models.TextField(blank=True, verbose_name='Kick Off Comment'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='last_automatic_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last automatic reminder sent on'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='mid_term_comment',
            field=models.TextField(blank=True, verbose_name='Mid Term Comment'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_status', to='dashboard.Team'),
        ),
    ]
