# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20161209_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='active',
            field=models.BooleanField(default=False, help_text='If this field is set to ON all the emails of the specified type will use this template. Each type of email can have only one default', verbose_name='Use this as default template of its type?'),
        ),
        migrations.AddField(
            model_name='email',
            name='name',
            field=models.CharField(default='A', help_text='Template name to uniquely identify it.', max_length=200, verbose_name='Name of the Template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(help_text="If you wish to include the url to consultant form in the email, please add 'FORM_URL' (without quotes) placeholder. It will be replaced by the actual consultant url in the email.", verbose_name='Body of the Email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('IM', 'Instruction Mail'), ('RM', 'Reminder Mail')], help_text='Type of the template. Currently Instruction Email template and Reminder Email template are supported.', max_length=5, verbose_name='Type of Email'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='automatic_reminder',
            field=models.BooleanField(default=True, help_text='Should periodic Automatic Reminders Emails be sent?', verbose_name='Send Automatic Reminders?'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='call_change_count',
            field=models.IntegerField(default=0, help_text='This value will be added to total calls count.', verbose_name='Add/Subtract Total Calls count'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='kick_off',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IMS', 'Intro Mail Sent'), ('DA', 'Date Arranged'), ('CH', 'Call Happened')], default='NS', max_length=5, verbose_name='Kick Off Status'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='last_automatic_reminder',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last automatic reminder sent on'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='mid_term',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IMS', 'Intro Mail Sent'), ('DA', 'Date Arranged'), ('CH', 'Call Happened')], default='NS', max_length=5, verbose_name='Mid Term Status'),
        ),
    ]
