# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_teamstatus_next_automatic_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='missing_calls',
            field=models.PositiveIntegerField(default=0, verbose_name='Missing Call count'),
        ),
        migrations.AlterField(
            model_name='member',
            name='participates_in_call',
            field=models.BooleanField(default=True, verbose_name='Participates in Calls'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='next_automatic_reminder',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Next automatic reminder will be sent on'),
        ),
    ]
