# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20161129_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LRP', 'LRP'), ('SA', 'Senior Advisor'), ('SC', 'Senior Consultant'), ('JC', 'Junior Consultant'), ('C', 'Consultant'), ('F', 'Fellow'), ('FC', 'Fellow Colleague')], max_length=3, verbose_name='Role')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Member'),
        ),
    ]
