# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20161210_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(help_text='Template name to uniquely identify it.', max_length=200, unique=True, verbose_name='Name of the Template'),
        ),
    ]
