# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_delete_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='missing_calls',
            new_name='missed_calls',
        ),
    ]
