# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20161129_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='member',
        ),
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AddField(
            model_name='role',
            name='long_name',
            field=models.CharField(default='LRP', max_length=18, verbose_name='Long Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='short_name',
            field=models.CharField(default='LRP', max_length=3, verbose_name='Short Name'),
            preserve_default=False,
        ),
    ]
