# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20161129_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Role'),
            preserve_default=False,
        ),
    ]
