# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170105_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatus',
            name='systemic_vision',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IMS', 'Intro Mail Sent'), ('DA', 'Date Arranged'), ('CH', 'Call Happened')], default='NS', max_length=5, verbose_name='Systemic Vision Status'),
        ),
        migrations.AddField(
            model_name='teamstatus',
            name='systemic_vision_comment',
            field=models.TextField(blank=True, verbose_name='Systemic Vision Comment'),
        ),
    ]
