# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20161210_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisoryphase',
            name='expected_calls',
        ),
        migrations.RemoveField(
            model_name='advisoryphase',
            name='reached_in_week',
        ),
        migrations.AddField(
            model_name='advisoryphase',
            name='phase_number',
            field=models.PositiveIntegerField(default=1, help_text="Phase are sorted according to this number. If phase 'A' should happen before phase 'B' then 'A' should have lower phase number value than 'B'.", verbose_name='Phase number'),
            preserve_default=False,
        ),
    ]
