# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170106_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstatus',
            name='advisor_onboarding',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IMS', 'Intro Mail Sent'), ('DA', 'Date Arranged'), ('CH', 'Call Happened')], default='NS', max_length=5, verbose_name='Advisor Onboarding Status'),
        ),
        migrations.AddField(
            model_name='teamstatus',
            name='advisor_onboarding_comment',
            field=models.TextField(blank=True, verbose_name='Kick Off Comment'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status_choice',
            field=models.CharField(choices=[('AUTO', 'Automatic'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green')], default='AUTO', max_length=7, verbose_name='Team status evaluation'),
        ),
    ]
