# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20161210_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_count', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Call count warning Type')),
                ('phase', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Current Phase warning type')),
                ('kick_off', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Kick Off warning type')),
                ('mid_term', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Mid Term warning type')),
                ('unprepared_call', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Unprepared calls warning type')),
                ('consultant_rating', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Consultant rating warning type')),
                ('fellow_rating', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('R', 'Red')], max_length=3, verbose_name='Fellow rating warning type')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='dashboard.Team')),
            ],
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='unprepared_calls_red_warning',
            field=models.IntegerField(default='30', help_text='If percentage of unprepared calls is less than this threshold, Red warning will be raised. ', verbose_name='% unprepared call threshold'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='unprepared_calls_yellow_warning',
            field=models.IntegerField(default='50', help_text='If percentage of unprepared calls is less than this threshold, Yellow warning will be raised. ', verbose_name='% unprepared call threshold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advisoryphase',
            name='phase',
            field=models.CharField(max_length=200, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='advisoryphase',
            name='phase_number',
            field=models.PositiveIntegerField(help_text="Phase are sorted according to this number. If phase 'A' should happen before phase 'B' then 'A' should have lower phase number value than 'B'.", unique=True, verbose_name='Phase number'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='member_call_red_warning',
            field=models.PositiveIntegerField(help_text='Person missing calls: > leads to Red warning (Should be greater than yellow warning member call count) ', verbose_name='Member missing call count - Red warning'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='member_call_yellow_warning',
            field=models.PositiveIntegerField(help_text='Person missing calls: > leads to Yellow warning', verbose_name='Member missing call count - Yellow warning'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='phase_red_warning',
            field=models.ForeignKey(blank=True, help_text='Red warning if in less than this Phase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_warning_phase', to='dashboard.AdvisoryPhase'),
        ),
        migrations.AlterField(
            model_name='weekwarning',
            name='phase_yellow_warning',
            field=models.ForeignKey(blank=True, help_text='Yellow warning if in this Phase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yellow_warning_phase', to='dashboard.AdvisoryPhase'),
        ),
    ]
