# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20161129_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit date')),
                ('call_date', models.IntegerField(verbose_name='Call date')),
                ('missing_member', models.CharField(blank=True, max_length=300, verbose_name='Missing members')),
                ('all_prepared', models.BooleanField(verbose_name='All participants prepared for call?')),
                ('topic_discussed', models.CharField(max_length=200, verbose_name='Topic Discussed')),
                ('help', models.CharField(blank=True, max_length=3000, verbose_name='Ashoka team should help with')),
                ('phase_rating', models.IntegerField(blank=True, null=True, verbose_name='How is the phase going?')),
                ('other_comments', models.CharField(blank=True, max_length=3000, verbose_name='Any other comments?')),
                ('document_link', models.URLField(blank=True, verbose_name='Link to current document')),
                ('current_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='dashboard.AdvisoryPhase')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='dashboard.Role'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.Dashboard'),
        ),
        migrations.AddField(
            model_name='fellowsurvey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='dashboard.Team'),
        ),
    ]
