# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20161210_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamWarnings',
            new_name='TeamWarning',
        ),
    ]
