# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170110_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisoryphase',
            options={'verbose_name_plural': 'Advisory Phases (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='consultantsurvey',
            options={'verbose_name': 'Consultant Survey (Optional)', 'verbose_name_plural': 'Consultant Surveys (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='fellowsurvey',
            options={'verbose_name': 'Fellow Survey (Optional)', 'verbose_name_plural': 'Fellow Surveys (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'Roles (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='secondaryrole',
            options={'verbose_name_plural': 'Secondary Roles (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teamstatus',
            options={'verbose_name': 'Team status (Optional)', 'verbose_name_plural': 'Team status (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='teamwarning',
            options={'verbose_name': 'Team Warnings (Optional)', 'verbose_name_plural': 'Team Warnings (Optional)'},
        ),
        migrations.AlterModelOptions(
            name='weekwarning',
            options={'verbose_name': 'Weekly Warnings (Optional)', 'verbose_name_plural': 'Weekly Warnings (Optional)'},
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='advisor_on',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Advisor Onboarding'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='advisor_on_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Advisory Onboarding'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='sys_vision',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Systemic Vision'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='sys_vision_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Systemic Vision'),
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='advisor_on_r',
            field=models.BooleanField(default=False, help_text='Advisor Onboarding not happened in this week leads to Red warning.', verbose_name='Advisor Onboarding - Red warning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='advisor_on_y',
            field=models.BooleanField(default=False, help_text='Advisor Onboarding not happened in this week leads to Yellow warning.', verbose_name='Advisor Onboarding - Yellow warning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='sys_vision_r',
            field=models.BooleanField(default=False, help_text='Systemic Vision not happened in this week leads to Red warning', verbose_name='Systemic Vision - Red warning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='sys_vision_y',
            field=models.BooleanField(default=False, help_text='Systemic Vision not happened in this week leads to Yellow warning', verbose_name='Systemic Vision - Yellow warning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='secondary_role',
            field=models.ManyToManyField(blank=True, related_name='secondary_role', to='dashboard.SecondaryRole'),
        ),
        migrations.AlterField(
            model_name='teamstatus',
            name='advisor_onboarding_comment',
            field=models.TextField(blank=True, verbose_name='Advisor Onboarding Comment'),
        ),
    ]
