# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20161130_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellowsurvey',
            name='call_date',
            field=models.DateField(verbose_name='Call date'),
        ),
    ]
