# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170124_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstatus',
            old_name='advisor_onboarding',
            new_name='advisor_on',
        ),
        migrations.RenameField(
            model_name='teamstatus',
            old_name='advisor_onboarding_comment',
            new_name='advisor_on_comment',
        ),
    ]
