# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20161210_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekwarning',
            name='calls_red_warning',
            field=models.PositiveIntegerField(help_text='Number of calls less than this value leads to Red warning (Should be less than yellow warning call count) ', verbose_name='Call count - Red warning'),
        ),
    ]
