# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20161130_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fellowsurvey',
            name='missing_member',
        ),
        migrations.AddField(
            model_name='fellowsurvey',
            name='missing_member',
            field=models.ManyToManyField(related_name='surveys', to='dashboard.Member'),
        ),
    ]
