# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20161210_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamwarning',
            name='call_count',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Call count warning Type'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='consultant_rating',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Consultant rating warning type'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='fellow_rating',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Fellow rating warning type'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='kick_off',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Kick Off warning type'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='mid_term',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Mid Term warning type'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='phase',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Current Phase warning type'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='unprepared_call',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Unprepared calls warning type'),
        ),
    ]
