# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 09:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20161204_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='Submit date')),
                ('phase_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the advisory phase going?')),
                ('comments', models.CharField(blank=True, max_length=3000, verbose_name='Any other comments?')),
                ('other_help', models.CharField(blank=True, max_length=3000, verbose_name='Any other Ashoka should help with?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellow_surveys', to='dashboard.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='consultantsurvey',
            name='phase_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='How is the advisory phase going?'),
        ),
        migrations.AlterField(
            model_name='consultantsurvey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_surveys', to='dashboard.Team'),
        ),
    ]
