# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20161210_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekwarning',
            name='rating_red_warning',
            field=models.PositiveIntegerField(default=7, help_text='Red warning if last rating by consultant is less than this value ', verbose_name='Phase Rating Red Warning'),
        ),
    ]
