# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20161204_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('RED', 'Major issues!!!'), ('YELLOW', 'Some minor issues!'), ('GREEN', 'All good!')], default='GREEN', max_length=7, verbose_name='Team Status'),
            preserve_default=False,
        ),
    ]
