# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20161130_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='receives_survey_reminder_emails',
            field=models.BooleanField(default=False, verbose_name='Receives reminder emails?'),
            preserve_default=False,
        ),
    ]
