# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lrp_comment',
            field=models.CharField(blank=True, max_length=4000, verbose_name='LRP Comment'),
        ),
    ]
