# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_weekwarning_rating_red_warning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultantsurvey',
            old_name='phase_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='fellowsurvey',
            old_name='phase_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='weekwarning',
            name='rating_red_warning',
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='consultant_rating_red_warning',
            field=models.PositiveIntegerField(default=7, help_text='Red warning if last rating by consultant is less than this value ', verbose_name='Consultant Rating Red Warning'),
        ),
        migrations.AddField(
            model_name='weekwarning',
            name='fellow_rating_red_warning',
            field=models.PositiveIntegerField(default=7, help_text='Red warning if last rating by consultant is less than this value ', verbose_name='Felloow Phase Rating Red Warning'),
        ),
    ]
