# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_team_lrp_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comment',
            field=models.CharField(blank=True, max_length=4000, verbose_name='comment'),
        ),
    ]
