# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_team_email_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email_language',
        ),
    ]
