# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_member_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('RED', 'Major issues!!!'), ('YELLOW', 'Some minor issues!'), ('GREEN', 'All good!')], default='GREEN', max_length=7, verbose_name='Team Status'),
        ),
    ]
