# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20161211_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='active',
            new_name='default',
        ),
    ]
