# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20161211_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamwarning',
            name='call_count_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Call Count'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='consultant_rating_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Consultant Rating'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='fellow_rating_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Fellow Rating'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='kick_off_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Kick Off'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='mid_term_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Mid Term'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='phase_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Phase'),
        ),
        migrations.AddField(
            model_name='teamwarning',
            name='unprepared_call_comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment - Unprepared Calls'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='call_count',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Call Count'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='consultant_rating',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Consultant Rating'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='fellow_rating',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Fellow Rating'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='kick_off',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Kick Off'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='mid_term',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Mid Term'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='phase',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Phase'),
        ),
        migrations.AlterField(
            model_name='teamwarning',
            name='unprepared_call',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='G', max_length=3, verbose_name='Warning - Unprepared Calls'),
        ),
    ]
