# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20161211_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekwarning',
            old_name='calls_red_warning',
            new_name='calls_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='calls_yellow_warning',
            new_name='calls_y',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='consultant_rating_red_warning',
            new_name='consultant_rating_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='fellow_rating_red_warning',
            new_name='fellow_rating_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='kick_off_red_warning',
            new_name='kick_off_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='kick_off_yellow_warning',
            new_name='kick_off_y',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='member_call_red_warning',
            new_name='member_call_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='member_call_yellow_warning',
            new_name='member_call_y',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='mid_term_red_warning',
            new_name='mid_term_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='mid_term_yellow_warning',
            new_name='mid_term_y',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='phase_red_warning',
            new_name='phase_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='phase_yellow_warning',
            new_name='phase_y',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='unprepared_calls_red_warning',
            new_name='unprepared_calls_r',
        ),
        migrations.RenameField(
            model_name='weekwarning',
            old_name='unprepared_calls_yellow_warning',
            new_name='unprepared_calls_y',
        ),
    ]
