# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_advisoryphase_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisoryphase',
            name='short',
        ),
    ]
